Fix for running babel in a symlinked directory
For my use case, I'm using yarn workspaces, however I want to be able to symlink a package under the workspace file structure. Due to the way yarn only installs babel packages in the root `node_modules` directory, without this change the directory resolves to the real location which then can't resolve any of the babel preset and plugin packages when it runs babel as part of the `install` and I end up with errors similar to the below.

```
Error: Couldn't find preset "env" relative to directory "src"
```