Fix `isIdentifer` check for result.deopt in @babel/preset-env
When using 7.0.0-beta-31, I consistently run into the following error within several babel plugins:

```
node_modules/@babel/preset-env/lib/use-built-ins-plugin.js:180
          } else if (result.deopt && result.deopt.isIdentifier()) {
                                             ^
TypeError: result.deopt.isIdentifier is not a function
```

It's the result.deopt.isIdentifer part that consistently breaks my builds, if the line is changed to use `t.isIdentifer(result.deopt)` everything works perfectly as expected.